services:
  postgres:
    container_name: postgres
    restart: always
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./postgres/.env
    expose:
      - 5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dump.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - project-network

  api:
    container_name: api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - ./api/.env.production
    volumes:
      - ./api:/usr/share/nginx/html/
      - storage:/usr/share/nginx/html/storage:rw
      - public:/usr/share/nginx/html/public:rw
    expose:
      - 9000
    networks:
      - project-network

  web:
    container_name: web
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    depends_on:
      - api
    env_file:
      - ./web/.env.production
    volumes:
      - ./web:/app
    expose:
      - 3000
    networks:
      - project-network

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - api
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./nginx/ssl:/etc/nginx/ssl
      - storage:/usr/share/nginx/html/storage:rw
      - public:/usr/share/nginx/html/public:ro
      - ./nginx/logs:/etc/nginx/logs
    networks:
      - project-network


networks:
  project-network:
    driver: bridge

volumes:
  storage:
    driver: local
  public:
    driver: local