export type InputFileTypes =
    | 'image/png'
    | 'image/jpeg'
    | 'image/jpg'
    | 'application/pdf'
    | 'application/zip'
    | 'text/plain'
    | 'image/gif'
    | 'image/svg+xml'
    | 'application/json'
    | '*/*'